### ISSUE TITLE
Rename `fields-wysiwyg-tinymce` to the singular form

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1350]
The `@keystone-alpha/fields-wysiwyg-tinymce` package contains only a single field, yet is named in the plural.

We should rename the package to the singular: `@keystone-alpha/field-wysiwyg-tinymce`

**Comment by gautamsi** [comment]
I think I commented this earlier somewhere.
We should rename this to `field-wysiwyg` and create `wysiwyg-tinymce-adapter`, this way anyone can create and swap out different adapters for WYSIWYG field.

**Comment by jesstelford** [comment]
I like this idea ☝️ It's the same pattern I used for the OEmbed block and OEmbed adapters. Works well!

**Comment by JedWatson** [comment]
> We should rename this to field-wysiwyg and create wysiwyg-tinymce-adapter, this way anyone can create and swap out different adapters for WYSIWYG field.

tbh I think this is unnecessary. The field type is already an extension of the core `Text` type, and almost every line of code is specific to tinymce. Other wysiwyg editors can easily be added (either in the monorepo or in userland) in the same way, creating another layer will not simplify it in any way that I can see.

> We should rename the package to the singular: @keystone-alpha/field-wysiwyg-tinymce

Pretty sure this has been debated in several places already; including on the PR where this field was added (#929). We're going to have some packages that provide _single fields_ and some that add _multiple fields_; and we may add additional field types over time to packages that used to provide only one (at which point renaming is way more invasive than being able to publish a minor bump). So we need to pick either single or plural, and we should be consistent. Either will be wrong some of the time.

My only small reason for preferring plural is it groups nicely with the `fields` package, which would otherwise be named `field` for consistency, and that just seems silly. (side point: there's an argument to be made to name that package `fields-core`, but that argument won't be made here)

To expand that, I prefer:

```js
import { Text, Integer } from '@keystone-alpha/fields';
import { Image, Images } from '@keystone-alpha/fields-cloudinary';
import { Wysiwyg } from '@keystone-alpha/fields-wysiwyg-tinymce';
```

over

```js
import { Text, Integer } from '@keystone-alpha/field';
import { Image, Images } from '@keystone-alpha/field-cloudinary';
import { Wysiwyg } from '@keystone-alpha/field-wysiwyg-tinymce';
```

With that bikeshed discussed, I'm going to close this with a quote from the original PR:

> I don't really care all that much. We just need to make sure we're consistent going forward 👍

We have a bunch of `fields-*` packages now (markdown, wysiwyg, id types) and it's consistent 👍
