### ISSUE TITLE
Documentation: KeystoneJS-5 Vs AWS AppSync Vs Hasura.io

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone-5#1395]
Do we have a comparison of Keystone-5 with AWS AppSync (https://aws.amazon.com/appsync/ ) and Hasura (https://hasura.io/ ) How should Keystone-5 be positioned?

**Comment by jesstelford** [comment]
Not yet, but I'd love to have one written up! Would also like to see a few others listed too; Prisma, CraftCMS, and Statamic to start.

Do you have experience with any of these? I've created a spreadsheet where we can start listing some features of each platform to get a sense of what's comparable and what's not. Feel free to add what you know! https://docs.google.com/spreadsheets/d/1bfO3hBX3tq90DrcCQ_wejytLmel7f7ZlCk4JG5dbxPI/edit?usp=sharing

**Comment by VinayaSathyanarayana** [comment]
Updated the Google Sheets file with initial thoughts ... Will add to you in the next few days.

**Comment by JedWatson** [comment]
(not sure how to capture this in the spreadsheet so dropping some thoughts here)

This is interesting because I have been thinking about how we could write keystone adapters to make it sit on top of either Hasura, AppSync or Prisma. Haven't looked deeply into how much work would be involved, but theoretically it's very possible.

Keystone's not really trying to be that "lowest level layer" to your database, although with mongoose and knex we have had to do a lot of heavy lifting in those adapters. AppSync in particular also provides some nice UI bindings that I don't expect we'll get to in Keystone (ours is more of a BYO frontend approach, with Apollo being used in our example projects)

Conversely Keystone leans more into the "help you build an app" space with Next.js integration (and hopefuly soon other frameworks), express server config, a dev + build process, etc.

Keystone also does some "higher level" things that (from what I know) those projects don't, including the whole _rich field types_ concept, having an extensible Admin UI framework that's designed to support high level workflows and data/content management, etc.

**Comment by MadeByMike** [comment]
What's the action required in this issue? Is it to create a comparison page in the documentation? If so I might rename the issue and we should clarify what we're looking to compare. Is it features, performance cost, usage... something else?

**Comment by VinayaSathyanarayana** [comment]
Agree with @JedWatson 

KeystoneJS should have an option to use Hasura, AppSync or Prisma as backend. 

Hasura provides GraphQL Subscriptions - What is the KeystoneJS view on that

**Comment by MadeByMike** [comment]
Closing this one as there is no real action required. Although it is great to be aware of similar products and services. We're not maintaining a public comparison list so I'm going to consider this a topic ongoing research and discussion better for our community slack: http://community.keystonejs.com.

**Comment by VinayaSathyanarayana** [comment]
We should have documentation on how to use Keystone on top of Hasura or AWS AppSync.
