### ISSUE TITLE
Can we remove the build step?

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone-5#1479]
If I make changes to a staticApp I need to run `yarn build` build to see these changes. I also need to run this the first time I start the adminUI? Could `yarn start` simply run build if it needs to?

**Comment by mitchellhamilton** [comment]
Build steps aren't run in the CLI when `keystone dev` is run which is what you should probably be running when you're making changes. If we automatically ran build steps in start, it could cause confusing errors because lots of hosting platforms have lower memory requirements for running a server than they do when building something so you could get an out of memory error because you forgot to build it but you wouldn't know that but with the current setup, you fail quickly and can fix it.

**Comment by jesstelford** [comment]
As @mitchellhamilton pointed out; build steps are to be run _before_ deploying the built code to your production server, not as part of starting the server.

In `dev` mode, we have a hot reloading server which does what you propose, but in `prod` mode, it requires the two-step process.
