### ISSUE TITLE
How does one actually query db data in KS5?

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone-5#1589]
This is probably a dumb question, but... what's the API for actually executing a query in KS5? In KS4 there was `keystone.list("foo").model.find` (mongoose queries). I can't figure out what functions actually accepts the new GraphQL strings 😬 The TODO demo in this repo doesn't enlighten me either... and the GraphQL API page in the docs is blank... Do you use `keystone.executeQuery`?

I can't figure out the whole business with Apollo either. Is that only necessary with the Next integration, but not static?

**Comment by jesstelford** [comment]
This is a great question! One we need to do a better job of answering in the docs.

1. `keystone.executeQuery` is what you'll use 99% of the time - it accepts a GraphQL query string and does all the heavy lifting for you in terms of optimising queries for the particular database adapter in use and resolving relationships, etc. I highly recommend trying this method first. Except when;
2. You can use the `query` action which is passed to hooks in the last argument. This is the same as `keystone.executeQuery` except it executes the query as the currently authenticated user (if your provide the `skipAccessControl: true` option to the second argument of `query`, it will behave identically to `keystone.executeQuery`.
3. To get access directly to the adapter and construct your own queries, there's no "official" API (really you should be using `keystone.executeQuery` wherever possible), but the escape hatch for now is the `keystone.adapters` object which you can play around with to do raw mongoose or SQL queries.

Apollo comes in two halves;
1. A GraphQL server implementation. We use this to power the `app-graphql` server. The fact that it's Apollo should be treated as an implementation detail.
1. A client library for making complex cached requests to any GraphQL API. While we use this in the Admin UI, it is 100% not necessary. In fact, the simplest was to query a GraphQL API is by sending a string in the body of a `fetch()`. The next simplest way is using the `graphql-request` npm library which has no caching or any other smarts. Then you get up into the kind-of smart query builders such as `urql` and `draqula`, and finally into the really complex caching mechanisms as used by `apollo` & `relay`.

**Comment by Vultraz** [comment]
Ah, thanks! (Sorry about the title - middle of the night frustration >_<).

So basically, you can either use `executeQuery` (I'm presuming you can `require` your index.js to get the running keystone instance) or `fetch()` for almost all common cases.

That does lead to a second question, though. Am I correct that the old "handle route, create a new `keystone.View` object, call `view.render("foo")`" workflow is no more? That is, all the stuff (like db querying) can now just be handled however you choose in your actual page code (using React, `appendChild`, etc)?

**Comment by jesstelford** [comment]
> Sorry about the title - middle of the night frustration

I can 100% relate! That's why it's a _good_ question, not a dumb question; if you can't figure it out then we have more work to do on the docs 👍 

> So basically, you can either use executeQuery (I'm presuming you can require your index.js to get the running keystone instance) or fetch() for almost all common cases.

Yes, this is correct - the `keystone` instance can be passed around / required where needed and it'll have everything ready to run `executeQuery`. For all your client-side or not-on-the-same-server needs, you can use a `fetch` (or other client-side GraphQL libraries).

> Am I correct that the old "handle route, create a new keystone.View object, call view.render("foo")" workflow is no more?

Yeah, we've removed the opinionated view layer from Keystone v5. We wanted to open the door to more client side libraries and frameworks (such as Next, Nuxt, Ember, Angular, etc). It also allowed us to rethink some architectural things inside Keystone which means we can focus more effort on providing a solid API layer.

It does, however, mean that you no longer get a view layer for free. We've tried to make it a bit easier by providing different ["Keystone `apps`"](https://v5.keystonejs.com/guides/apps) which have a simple interface ready to hook into the Express pipeline (for example, see the [`@keystone-alpha/app-next` package](https://github.com/keystonejs/keystone-5/tree/master/packages/app-next)).

**Comment by Vultraz** [comment]
IIUC, you still need a custom server setup (your `server.js` file) for additional custom route handling beyond what the apps offers (such as for an SPA), right? And I'm guessing if you have a custom server, you won't need to use the apps either?

**Comment by MadeByMike** [comment]
@Vultraz, yes a custom server could replace apps but you can also use a custom server with apps. I'd suggest using apps might be a better first approach before replacing the default server. 

I'd save using a custom server until you really need it. Ie; When you need to do something you can't with apps. See some of the examples here: https://v5.keystonejs.com/guides/custom-server

**Comment by MadeByMike** [comment]
BTW is you are after a SPA - the StaticApp is probably what you want.  https://v5.keystonejs.com/keystone-alpha/app-static/ Set the fallback route to your SPA index file and all routes will be redirected there.
